/* Tests for libtetrisauth's entry point.
 *
 * Phase 4 (#54). One file, three sections, split at #55's line rather than at
 * "unit vs integration", following tests/test_db.c's macro and
 * driver shape:
 *
 *   A. No socket, no server   #58's jwt_secret fixtures, which are pure
 *                             return-value checks against auth_secret_load().
 *   B. Socketpair, scripted peer   auth_retry_handler() and auth_offer(): the
 *                             control flow, the status mapping, both
 *                             degradations, and the scrub.
 *   C. Live SocketRunner   the queries themselves, skipped without a JVM.
 *
 * Three things about this suite that are decisions, not omissions:
 *
 *   - EVERY CASE IN B AND C FORKS. #55's file-statics never reset and the
 *     config load freezes on first success, so a case that wants a different
 *     auth_max_attempts or a fresh counter gets one by being a child process.
 *     That is the design being tested honestly: one process, one client. There
 *     is deliberately no auth_reset_for_test().
 *   - NO CASE ASSERTS ON ELAPSED WALL-CLOCK TIME, including the two that exist
 *     to pin deadlines. Both assert a 500 under an alarm() watchdog, which
 *     distinguishes "returned with the right answer" from "hung" with no
 *     tolerance to tune.
 *   - TETRISH_REQUIRE_RUNNER=1 turns a skip into a failure, and CI sets it.
 *     The skip line names `java` and the jar separately, because they are
 *     different problems with different fixes and one message for both is why
 *     nobody noticed the database tests had never run on a push.
 *
 * The two load-bearing cases, so they are not read as ordinary coverage: the
 * four-process registration sweep over growing pre-fill counts (four children
 * against an empty table all land on page 0, which has free slots, so the
 * transaction alone is sufficient there and the case passes on a build with
 * the semaphore deleted), and GUEST succeeding with the database provably
 * absent.
 *
 * WHERE #54's SECTION LINE MOVED, AND WHY. #55's resolution expected
 * auth_offer() to be reachable "with no socket and no server", because it
 * takes a parsed request and a SessionState. That is still false, for a
 * smaller reason than it used to be: it answers 409 on the wire itself, so it
 * needs the session auth_retry_handler() retained. Every auth_offer() case is
 * therefore in section B, and the pure rules underneath it - the body split,
 * the username allowlist, the password bounds - are asserted through the wire
 * rather than by reaching into core/src/libtetrisauth/auth.h, which is
 * private for the same reason token.c's parsing statics are.
 *
 * ONE CASE ASSERTS A DELETED MECHANISM BY ITS ABSENCE. #48 decision 3 was
 * overturned after this suite was first written: guest is terminal, so no
 * credential can be offered after the exchange resolves, so nothing post-login
 * can spend an attempt and the shutdown()-as-drop-channel is gone. The refusal
 * case offers five auth methods against auth_max_attempts of 2 and requires
 * the connection to survive all five. Delete that case and the mechanism can
 * come back unnoticed.
 *
 * Full checklist: #54, plus #58's five secret-file cases.
 *
 * === #58's secret-file cases (Section A) ===
 *
 * All fixtures under one temp TETRISH_ROOT, no JVM, no fork - varying a file
 * on disk rather than an rc value holds no static and needs none of the
 * process-isolation the rest of this suite pays for. #56 means a 500 never
 * moves the attempt counter, so these are pure return-value checks against
 * auth_secret_load() directly.
 *
 * NOTHING HERE CREATES A SECRET, and no case asserts that anything does. The
 * key is generated by the `secret` target in the Makefile, not by
 * libtetrisauth, so that a login handler cannot mint a signing key and
 * silently rotate every outstanding token. The absent case below therefore
 * expects a refusal, and it is the assertion that pins that split.
 *
 * Run from the repo root: make test */
#include "test_output.h"
#include <errno.h>
#include <fcntl.h>
#include <semaphore.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <unistd.h>

#include "libhtttp/htttp.h"
#include "libtetrisauth/auth.h"
#include "auth.h"
#include "secret.h"
#include "libtetrisdb/schema.h"
#include "libtetrisdb/socket/conf.h"
#include "libtetrisdb/socket/db.h"
#include "libtetrissh/tetrissh.h"
#include "libtetrisutil/sessionstate.h"
#include "runner.h"

#define TEST_ROOT "var/auth_test"
#define TEST_SECRET_PATH TEST_ROOT "/auth/jwt_secret"

/* Section B and C build an isolated working directory. Each child chdirs into
 * it before auth_retry_handler(), so relative auth paths cannot touch the
 * developer's real .tetrishrc or auth/jwt_secret. */
#define WIRE_ROOT "var/auth_wire"
#define WIRE_RC WIRE_ROOT "/.tetrishrc"
#define WIRE_SECRET WIRE_ROOT "/auth/jwt_secret"
#define WIRE_DB WIRE_ROOT "/db"
#define WIRE_SOCK WIRE_ROOT "/run/tetrisdb.sock"
#define WIRE_SILENT WIRE_ROOT "/run/silent.sock"
#define TEST_JAR "db/dist/simpledb.jar"

/* Kills the process if a case that must not block does. Asserts "it returned",
 * not "it returned within N ms", so there is no threshold to tune. */
#define WATCHDOG_SECS 20

/* Low enough that the four-process sweep costs a fraction of a second and high
 * enough to still be a real PBKDF2 call. #60 decision 8 granted the key for
 * exactly this, and refused a floor: any floor low enough for a test stops
 * nobody in production. */
#define TEST_ITERS "1000"

static int tests_run = 0, tests_failed = 0, tests_skipped = 0;

#define CHECK(cond, msg)                                                       \
    do                                                                         \
    {                                                                          \
        if (!(cond))                                                           \
        {                                                                      \
            test_output_failure_detail(msg, __FILE__, __LINE__);               \
            return -1;                                                         \
        }                                                                      \
    } while (0)

static void run(const char *name, int (*fn)(void))
{
    tests_run++;
    if (fn() != 0)
    {
        tests_failed++;
        test_output_fail(name);
    }
    else
        test_output_pass(name);
}

static void reset_root(void)
{
    (void)unlink(TEST_SECRET_PATH);
    (void)rmdir(TEST_ROOT "/auth");
    (void)rmdir(TEST_ROOT);
}

static void make_dir(void)
{
    (void)mkdir(TEST_ROOT, 0700);
    (void)mkdir(TEST_ROOT "/auth", 0700);
}

/*
 * Write len arbitrary bytes to TEST_SECRET_PATH at the given mode. Returns 0
 * or -1, and the caller must CHECK it: a silently failed fixture leaves the
 * file ABSENT, and four of the cases below expect -1 from an absent file too,
 * so an unchecked failure here passes them for entirely the wrong reason.
 */
static int write_secret(size_t len, mode_t mode)
{
    unsigned char buf[64];
    int fd = open(TEST_SECRET_PATH, O_CREAT | O_WRONLY | O_TRUNC, mode);
    if (fd < 0)
        return -1;

    memset(buf, 'k', sizeof buf);
    size_t written = 0;
    while (written < len)
    {
        size_t chunk = len - written;
        if (chunk > sizeof buf)
            chunk = sizeof buf;
        ssize_t n = write(fd, buf, chunk);
        if (n <= 0)
        {
            close(fd);
            return -1;
        }
        written += (size_t)n;
    }
    close(fd);

    /* O_CREAT's mode is masked by umask, so set it explicitly. */
    return chmod(TEST_SECRET_PATH, mode);
}

/* --- the five no-socket cases --- */

static int test_absent_is_500(void)
{
    reset_root();
    make_dir();

    unsigned char out[64];
    int rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    CHECK(rc == -1, "absent secret must be refused, not created");

    reset_root();
    return 0;
}

static int test_loose_mode_is_500(void)
{
    reset_root();
    make_dir();
    CHECK(write_secret(32, 0644) == 0, "fixture: write a 0644 secret");

    unsigned char out[64];
    int rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    CHECK(rc == -1, "group/other-readable secret must be refused");

    reset_root();
    return 0;
}

static int test_short_secret_is_500(void)
{
    reset_root();
    make_dir();
    CHECK(write_secret(31, 0600) == 0, "fixture: write a 31-byte secret");

    unsigned char out[64];
    int rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    CHECK(rc == -1,
          "a 31-byte secret is below RFC 7518's floor and must be refused");

    reset_root();
    return 0;
}

static int test_oversized_secret_is_500(void)
{
    reset_root();
    make_dir();
    CHECK(write_secret(65, 0600) == 0, "fixture: write a 65-byte secret");

    unsigned char out[128];
    int rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    CHECK(rc == -1,
          "a 65-byte secret is above the HMAC block size and must be refused");

    reset_root();
    return 0;
}

/*
 * A FIFO is the case S_ISREG exists for, and it is the one that cannot be
 * caught by asserting on a return value alone: a bare open(O_RDONLY) on a
 * FIFO BLOCKS UNTIL A WRITER APPEARS, so the check never runs and the session
 * hangs holding a client that has already handshaked. This case was written
 * against exactly that bug and reproduced it.
 *
 * The watchdog is the assertion. It distinguishes "refused" from "never
 * returned" with no elapsed time to measure and no threshold to tune, which
 * is this suite's rule for every case that could hang.
 */
static int test_fifo_is_refused_not_read(void)
{
    reset_root();
    make_dir();
    CHECK(mkfifo(TEST_SECRET_PATH, 0600) == 0, "fixture: mkfifo");

    unsigned char out[64];
    alarm(WATCHDOG_SECS);
    int rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    alarm(0);
    CHECK(rc == -1, "a FIFO must be refused on S_ISREG, not opened and read");

    reset_root();
    return 0;
}

static int test_valid_secret_loads(void)
{
    reset_root();
    make_dir();
    CHECK(write_secret(32, 0600) == 0, "fixture: write a 32-byte secret");

    unsigned char out[64];
    int rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    CHECK(rc == 32, "a 32-byte, 0600 secret must load and return its length");

    reset_root();
    return 0;
}

/* The chmod recovery: 0644 refuses, chmod 0600 in place, the very next
 * attempt in the same process succeeds - no restart, nothing cached. */
static int test_chmod_recovers_without_restart(void)
{
    reset_root();
    make_dir();
    CHECK(write_secret(32, 0644) == 0, "fixture: write a 0644 secret");

    unsigned char out[64];
    int rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    CHECK(rc == -1, "first attempt against a loose file must be refused");

    CHECK(chmod(TEST_SECRET_PATH, 0600) == 0, "chmod 0600 must succeed");

    rc = auth_secret_load(TEST_ROOT, out, sizeof out);
    CHECK(rc == 32,
          "the same process, same file, must recover with no restart");

    reset_root();
    return 0;
}

/* The loader never repairs - it validates or refuses, and it never calls
 * chmod on a file it did not create. Creation belongs to `make secret`, so a
 * loose secret staying loose is the whole point rather than a missing repair.
 */
static int test_load_never_repairs(void)
{
    reset_root();
    make_dir();
    CHECK(write_secret(32, 0644) == 0, "fixture: write a 0644 secret");

    unsigned char out[64];
    CHECK(auth_secret_load(TEST_ROOT, out, sizeof out) == -1,
          "loading a loose existing secret must refuse, not repair");

    struct stat st;
    CHECK(stat(TEST_SECRET_PATH, &st) == 0, "the file must still be there");
    CHECK((st.st_mode & 0777) == 0644,
          "the loader must not have touched the mode");

    reset_root();
    return 0;
}

/* === B. Socketpair, scripted peer ======================================== */

/*
 * The session pair is hand-built rather than handshaked.
 *
 * session_t is three fields and libtetrissh's traffic functions ask only that
 * `established` is set and that both ends hold the same key, so two structs
 * over a socketpair speak exactly the frames a real session speaks. Running a
 * real session_accept() here would add an RSA handshake, a certificate on
 * disk and a second fork to every case in this section, and would test
 * libtetrissh, which tests/test_session.c already does.
 */
static void fake_session(session_t *s, int fd)
{
    memset(s, 0, sizeof *s);
    memset(s->key, 0x5a, sizeof s->key);
    s->fd = fd;
    s->established = 1;
}

static int write_file(const char *path, const void *data, size_t len,
                      mode_t mode)
{
    int fd = open(path, O_CREAT | O_WRONLY | O_TRUNC, mode);
    if (fd < 0)
        return -1;
    if (len > 0 && write(fd, data, len) != (ssize_t)len)
    {
        close(fd);
        return -1;
    }
    close(fd);
    return chmod(path, mode);
}

static void wire_reset(void)
{
    (void)unlink(WIRE_RC);
    (void)unlink(WIRE_SECRET);
    (void)unlink(WIRE_DB "/catalog.txt");
    (void)unlink(WIRE_DB "/user.dat");
    (void)unlink(WIRE_SOCK);
    (void)unlink(WIRE_SILENT);
    (void)rmdir(WIRE_ROOT "/auth");
    (void)rmdir(WIRE_ROOT "/run");
    (void)rmdir(WIRE_DB);
    (void)rmdir(WIRE_ROOT);
}

/* Build an isolated working directory with a 32-byte 0600 secret and the
 * relative paths each child uses. The child chdirs here before
 * auth_retry_handler(), so no case can touch the repo's own .tetrishrc or
 * auth/jwt_secret. */
static int wire_setup(void)
{
    unsigned char secret[32];

    wire_reset();
    (void)mkdir(WIRE_ROOT, 0700);
    (void)mkdir(WIRE_ROOT "/auth", 0700);
    (void)mkdir(WIRE_ROOT "/run", 0700);
    (void)mkdir(WIRE_DB, 0700);

    memset(secret, 0x2b, sizeof secret);
    return write_file(WIRE_SECRET, secret, sizeof secret, 0600);
}

/* rc == NULL removes the file, which is #60 decision 3's case. */
static int wire_rc(const char *rc)
{
    if (rc == NULL)
    {
        (void)unlink(WIRE_RC);
        return 0;
    }
    return write_file(WIRE_RC, rc, strlen(rc), 0600);
}

/* --- the scripted peer's two verbs --- */

static int put(session_t *cli, const char *method, const char *path,
               const char *body)
{
    htttp_request_t req;
    uint8_t out[2048];
    uint32_t out_len = sizeof out;

    memset(&req, 0, sizeof req);
    snprintf(req.method, sizeof req.method, "%s", method);
    snprintf(req.path, sizeof req.path, "%s", path);
    if (body != NULL)
    {
        req.body = (const uint8_t *)body;
        req.body_len = (uint32_t)strlen(body);
    }
    if (htttp_serialize_request(&req, out, &out_len) != HTTTP_OK)
        return -1;
    return session_send(cli, out, out_len) == SESSION_OK ? 0 : -1;
}

/* The status of the next response, or -1 if the peer hung up or sent
 * something that is not one. body, when given, receives the NUL-terminated
 * body - which is where the token rides. */
static int get(session_t *cli, char *body, size_t cap)
{
    uint8_t buf[SESSION_MAX_FRAME];
    uint32_t len = sizeof buf;
    htttp_response_t res;

    if (body != NULL && cap > 0)
        body[0] = '\0';
    if (session_recv(cli, buf, &len) != SESSION_OK)
        return -1;
    if (htttp_parse_response(buf, len, &res) != HTTTP_OK)
        return -1;
    if (body != NULL && cap > 0 && res.body != NULL && res.body_len < cap)
    {
        memcpy(body, res.body, res.body_len);
        body[res.body_len] = '\0';
    }
    return res.status;
}

/* --- the driver --- */

typedef struct
{
    const char *rc;              /* .tetrishrc contents, or NULL for none    */
    int (*child)(session_t *sh); /* runs in the forked session process       */
    int (*peer)(session_t *cli); /* runs here, scripting the client          */
} wire_case_t;

/*
 * Run one case: the child is the session, this process is the client.
 *
 * The child's EXIT CODE IS ITS ASSERTION - every child below returns a
 * distinct small integer per thing it checked, because a child cannot use
 * CHECK() and printing from it would interleave with this process's output.
 */
static int drive(const wire_case_t *w)
{
    int sv[2];

    CHECK(wire_rc(w->rc) == 0, "fixture: write .tetrishrc");
    CHECK(socketpair(AF_UNIX, SOCK_STREAM, 0, sv) == 0, "socketpair");

    pid_t pid = fork();
    CHECK(pid >= 0, "fork");
    if (pid == 0)
    {
        session_t sh;

        close(sv[0]);
        if (chdir(WIRE_ROOT) != 0)
            _exit(250);
        alarm(WATCHDOG_SECS);
        fake_session(&sh, sv[1]);
        _exit(w->child(&sh));
    }
    close(sv[1]);

    session_t cli;
    fake_session(&cli, sv[0]);
    int rc = w->peer(&cli);
    close(sv[0]);

    int status = 0;
    while (waitpid(pid, &status, 0) < 0 && errno == EINTR)
        ;

    if (rc != 0)
        return -1;
    CHECK(WIFEXITED(status), "the session child died rather than returning");
    if (WEXITSTATUS(status) != 0)
        test_output_failure_detailf(__FILE__, __LINE__,
                                    "the session child failed assertion %d",
                                    WEXITSTATUS(status));
    CHECK(WEXITSTATUS(status) == 0, "the session child reported a failure");
    return 0;
}

/* The child every case with nothing to check after the exchange uses. */
static int child_expect_ok(session_t *sh)
{
    return auth_retry_handler(sh) == AUTH_OK ? 0 : 1;
}

static int child_expect_drop(session_t *sh)
{
    return auth_retry_handler(sh) == AUTH_DROP ? 0 : 1;
}

/* --- B cases --- */

/*
 * LOAD-BEARING. GUEST with the database provably absent.
 *
 * db_ipc names a socket that does not exist, so anything on this path that
 * reached for the database would fail loudly rather than silently pass. This
 * and the prompt-500 case below are the only tests in the suite that REQUIRE
 * the runner's absence, which is what makes them the only ones that cannot be
 * skipped into uselessness on a box with no JVM.
 */
static const char RC_NO_DB[] = "db_ipc = run/nothing-here.sock\n"
                               "db_timeout = 300\n"
                               "auth_pbkdf2_iters = " TEST_ITERS "\n";

static int child_guest_is_nameless(session_t *sh)
{
    char name[MAX_USER_NAME];

    if (auth_retry_handler(sh) != AUTH_OK)
        return 1;

    /* Before any login at all, and after an accepted GUEST, the stamp is empty
     * - which is what makes room.c fall back to "Player %d". */
    auth_get_name(name, sizeof name);
    return name[0] == '\0' ? 0 : 2;
}

static int peer_guest(session_t *cli)
{
    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200,
          "GUEST must be 200 with no database at all");
    return 0;
}

static int test_guest_needs_no_database(void)
{
    wire_case_t w = {RC_NO_DB, child_guest_is_nameless, peer_guest};
    return drive(&w);
}

/* A client that completes the handshake and then leaves is a drop, and the
 * caller closes exactly as it does today for a client that hung up. */
static int peer_hangup(session_t *cli)
{
    (void)cli;
    return 0;
}

static int test_hangup_is_a_drop(void)
{
    wire_case_t w = {RC_NO_DB, child_expect_drop, peer_hangup};
    return drive(&w);
}

/* A frame that is not a request is 400 and the exchange carries on: it is a
 * broken client, not a wrong password, so it costs no attempt. */
static int peer_garbage_then_guest(session_t *cli)
{
    const char junk[] = "this is not a request line";

    CHECK(session_send(cli, (const uint8_t *)junk, sizeof junk - 1) ==
              SESSION_OK,
          "send junk");
    CHECK(get(cli, NULL, 0) == 400, "an unparseable frame must be 400");
    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200, "the exchange must survive a 400");
    return 0;
}

static int test_unparseable_frame_is_400(void)
{
    wire_case_t w = {RC_NO_DB, child_expect_ok, peer_garbage_then_guest};
    return drive(&w);
}

/*
 * The pre-auth gate answers 401, and that 401 DOES NOT COUNT.
 *
 * auth_max_attempts is 2 here, and four JOINs go out before the GUEST. If the
 * counter moved on a refusal that answers a JOIN, the connection would be gone
 * before the GUEST arrived - and the server's count would also be out of step
 * with the client's, which mirrors AUTH_STATUS_COUNTS() and scopes it by the
 * method it is waiting on.
 */
static const char RC_TWO_ATTEMPTS[] = "db_ipc = run/nothing-here.sock\n"
                                      "db_timeout = 300\n"
                                      "auth_max_attempts = 2\n"
                                      "auth_pbkdf2_iters = " TEST_ITERS "\n";

static int peer_joins_then_guest(session_t *cli)
{
    for (int i = 0; i < 4; i++)
    {
        CHECK(put(cli, "JOIN", "/room/0", NULL) == 0, "send JOIN");
        CHECK(get(cli, NULL, 0) == 401, "a pre-auth JOIN must be 401");
    }
    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200,
          "four pre-auth 401s must not have spent the attempt budget");
    return 0;
}

static int test_pre_auth_401_does_not_count(void)
{
    wire_case_t w = {RC_TWO_ATTEMPTS, child_expect_ok, peer_joins_then_guest};
    return drive(&w);
}

/* Everything a malformed credential can be, all of it decided before any
 * connection is opened - which is what asserting 400 rather than 500 proves,
 * since db_ipc names nothing. */
static int peer_bad_bodies(session_t *cli)
{
    CHECK(put(cli, "LOGIN", "/auth/login", "no-newline-here") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 400, "a body with no LF must be 400");

    CHECK(put(cli, "LOGIN", "/auth/login", "\npassword") == 0, "send LOGIN");
    CHECK(get(cli, NULL, 0) == 400, "an empty username must be 400");

    CHECK(put(cli, "LOGIN", "/auth/login", "bob\n") == 0, "send LOGIN");
    CHECK(get(cli, NULL, 0) == 400, "an empty password must be 400");

    CHECK(put(cli, "LOGIN", "/auth/login", "bo b\npassword") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 400,
          "a username outside the allowlist must be 400");

    CHECK(put(cli, "LOGIN", "/auth/login", "o'brien\npassword") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 400, "a quote in a username must be 400");

    CHECK(put(cli, "LOGIN", "/auth/login", "sixteencharname1\npassword") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 400, "a 16-character username must be 400");

    CHECK(put(cli, "REGISTER", "/auth/register", "bob\nshort") == 0,
          "send REGISTER");
    CHECK(get(cli, NULL, 0) == 400,
          "a password under 8 bytes must be 400 at REGISTER");

    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200,
          "no 400 may have counted against the budget");
    return 0;
}

/* The cap is 15 INCLUSIVE, and a boundary asserted only from the refusing side
 * passes on an implementation that is off by one in the permissive direction.
 * A 500 here means the name was accepted and the exchange reached a database
 * that is not there, which is the only way to see "not refused" without one. */
static int peer_name_boundary(session_t *cli)
{
    CHECK(put(cli, "LOGIN", "/auth/login", "fifteenchars_ok\npassword") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 500,
          "a legal 15-character name must reach the database, not be refused");

    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200, "a 500 must not have spent an attempt");
    return 0;
}

static int test_malformed_credentials_are_400(void)
{
    wire_case_t w = {RC_NO_DB, child_expect_ok, peer_bad_bodies};
    return drive(&w);
}

static int test_legal_name_reaches_the_database(void)
{
    wire_case_t w = {RC_NO_DB, child_expect_ok, peer_name_boundary};
    return drive(&w);
}

/*
 * The deadline, pinned without measuring anything.
 *
 * A listener that accepts and never speaks is the case socket.h's deadline
 * exists for and the one nothing else catches: the socket is there, the
 * connect succeeds, and <<READY>> never arrives, so without a deadline this
 * hangs forever holding a client that has already handshaked. The assertion is
 * that a 500 comes back at all, under the child's alarm() - there is no
 * elapsed time here to compare against a threshold.
 */
static const char RC_SILENT_DB[] = "db_ipc = run/silent.sock\n"
                                   "db_timeout = 300\n"
                                   "auth_pbkdf2_iters = " TEST_ITERS "\n";

static int silent_listener(void)
{
    struct sockaddr_un addr;
    int fd = socket(AF_UNIX, SOCK_STREAM, 0);

    if (fd < 0)
        return -1;
    memset(&addr, 0, sizeof addr);
    addr.sun_family = AF_UNIX;
    snprintf(addr.sun_path, sizeof addr.sun_path, "%s", WIRE_SILENT);
    (void)unlink(WIRE_SILENT);
    if (bind(fd, (struct sockaddr *)&addr, sizeof addr) != 0 ||
        listen(fd, 8) != 0)
    {
        close(fd);
        return -1;
    }
    return fd;
}

static int peer_silent_db(session_t *cli)
{
    CHECK(put(cli, "LOGIN", "/auth/login", "bob\npassword") == 0, "send LOGIN");
    CHECK(get(cli, NULL, 0) == 500,
          "a runner that never greets must produce a 500, not a hang");

    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200,
          "a 500 must neither count nor stop the client becoming a guest");
    return 0;
}

static int test_silent_runner_is_500(void)
{
    wire_case_t w = {RC_SILENT_DB, child_expect_ok, peer_silent_db};

    int fd = silent_listener();
    CHECK(fd >= 0, "fixture: a listener that never speaks");
    int rc = drive(&w);
    close(fd);
    (void)unlink(WIRE_SILENT);
    return rc;
}

/*
 * No .tetrishrc at all: LOGIN and REGISTER are 500 and GUEST is untouched.
 *
 * That split is #60 decision 3's, and it is forced by #52's invariant A -
 * making the whole exchange fail would break the one path the availability
 * direction exists to protect.
 */
static int peer_no_rc(session_t *cli)
{
    CHECK(put(cli, "LOGIN", "/auth/login", "bob\npassword") == 0, "send LOGIN");
    CHECK(get(cli, NULL, 0) == 500, "an unreadable config must fail LOGIN");

    CHECK(put(cli, "REGISTER", "/auth/register", "bob\npassword1") == 0,
          "send REGISTER");
    CHECK(get(cli, NULL, 0) == 500, "an unreadable config must fail REGISTER");

    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200,
          "an unreadable config must not touch GUEST");
    return 0;
}

static int test_missing_rc_splits_guest_from_login(void)
{
    wire_case_t w = {NULL, child_expect_ok, peer_no_rc};
    return drive(&w);
}

/* --- auth_offer(), which needs the session auth_retry_handler() retained ---
 */

/* Build a parsed request the way session.c's POLLIN arm does: serialize into a
 * buffer and parse it back, so req->body points into buf exactly as his does
 * and the scrub has something real to clear. */
static int build_request(uint8_t *buf, size_t cap, htttp_request_t *req,
                         const char *method, const char *path, const char *body)
{
    htttp_request_t out;
    uint32_t len = (uint32_t)cap;

    memset(&out, 0, sizeof out);
    snprintf(out.method, sizeof out.method, "%s", method);
    snprintf(out.path, sizeof out.path, "%s", path);
    if (body != NULL)
    {
        out.body = (const uint8_t *)body;
        out.body_len = (uint32_t)strlen(body);
    }
    if (htttp_serialize_request(&out, buf, &len) != HTTTP_OK)
        return -1;
    return htttp_parse_request(buf, len, req) == HTTTP_OK ? 0 : -1;
}

/* Substring search over a buffer that may hold NULs. Written here rather than
 * calling memmem(), which is not in every libc this might be built against. */
static int contains(const uint8_t *hay, size_t hay_len, const char *needle)
{
    size_t n = strlen(needle);

    if (n == 0 || hay_len < n)
        return 0;
    for (size_t i = 0; i + n <= hay_len; i++)
        if (memcmp(hay + i, needle, n) == 0)
            return 1;
    return 0;
}

/*
 * Identity is fixed by the pre-auth exchange, so every credential offered
 * afterwards is refused - in every state, by every method, with no exchange
 * run and no attempt spent.
 *
 * The states are swept rather than sampled because "409 in every state" is the
 * whole rule: an implementation that consulted SessionState and got one arm
 * wrong would pass a single-state case.
 */
static int child_offer(session_t *sh)
{
    uint8_t buf[2048];
    htttp_request_t req;
    SessionState idle, in_room, playing;

    if (auth_retry_handler(sh) != AUTH_OK)
        return 1;

    memset(&idle, 0, sizeof idle);
    idle.phase = SESSION_IDLE;
    idle.room_id = ROOM_NONE;
    in_room = idle;
    in_room.phase = SESSION_WAITING;
    in_room.room_id = 3;
    playing = in_room;
    playing.phase = SESSION_PLAYING;

    /* Not one of the three methods: consumed nothing, answered nothing, and the
     * dispatch switch below it carries on untouched. */
    if (build_request(buf, sizeof buf, &req, "JOIN", "/room/0", NULL) != 0)
        return 2;
    if (auth_offer(&req, &idle))
        return 3;

    if (build_request(buf, sizeof buf, &req, "GUEST", "/auth/guest", NULL) != 0)
        return 4;
    if (!auth_offer(&req, &idle))
        return 5;

    if (build_request(buf, sizeof buf, &req, "REGISTER", "/auth/register",
                      "bob\npassphrase") != 0)
        return 6;
    if (!auth_offer(&req, &in_room))
        return 7;

    /* Idle is the state the superseded design ran the exchange in, so it is the
     * one most likely to grow an exception back. With db_ipc naming nothing, a
     * 409 rather than a 500 is also proof that no connection was attempted. */
    if (build_request(buf, sizeof buf, &req, "LOGIN", "/auth/login",
                      "bob\nhunter2hunter2") != 0)
        return 8;
    if (!auth_offer(&req, &idle))
        return 9;

    /* THE PLAINTEXT IS GONE BY THE TIME CONTROL COMES BACK. Refusing the
     * request does not unread it, and this is the one scrub in the design
     * reachable from a test, because it happens in the caller's buffer rather
     * than in a frame that has already returned. */
    if (contains(buf, sizeof buf, "hunter2hunter2"))
        return 10;

    /* Nothing above may have spent an attempt: auth_max_attempts is 2 here,
     * four offers went out, and the session must still be alive. */
    if (build_request(buf, sizeof buf, &req, "LOGIN", "/auth/login",
                      "bob\npassword") != 0)
        return 11;
    if (!auth_offer(&req, &idle))
        return 12;

    return 0;
}

static int peer_offer(session_t *cli)
{
    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200, "GUEST resolves the pre-auth exchange");

    CHECK(get(cli, NULL, 0) == 409, "GUEST after the exchange must be 409");
    CHECK(get(cli, NULL, 0) == 409, "REGISTER in a room must be 409");
    CHECK(get(cli, NULL, 0) == 409,
          "LOGIN while idle must be 409 too, with no database touched");
    CHECK(get(cli, NULL, 0) == 409, "the fifth offer must still be answered");
    return 0;
}

/*
 * auth_max_attempts is 2, and five auth methods are offered after login. On
 * the superseded design the second counted failure sent a final 401 and then
 * shutdown() the session fd; here no post-login response can count, so the
 * connection survives all five. That is the deleted mechanism asserted by its
 * absence, which is the only way left to assert it.
 */
static int test_offer_always_refuses(void)
{
    wire_case_t w = {RC_TWO_ATTEMPTS, child_offer, peer_offer};
    return drive(&w);
}

/* === C. Live SocketRunner ================================================ */

/* The two things a runner needs, asked separately: they are different problems
 * with different fixes, and one answer for both is why nobody noticed these
 * tests had never run on a push. */
/* Has the caller opted out of everything needing a real runner? `make test-ci`
 * sets it, because CI has no usable java. Checked before have_java(), so the
 * probe never runs, and it outranks TETRISH_REQUIRE_RUNNER: a deliberate
 * opt-out is not a regression. */
static int runner_disabled(void)
{
    return getenv("TETRISH_NO_RUNNER") != NULL;
}

static int have_jar(void)
{
    return access(TEST_JAR, R_OK) == 0;
}

static int have_java(void)
{
    pid_t pid = fork();
    if (pid < 0)
        return 0;
    if (pid == 0)
    {
        int null_fd = open("/dev/null", O_WRONLY);
        if (null_fd >= 0)
        {
            dup2(null_fd, STDOUT_FILENO);
            dup2(null_fd, STDERR_FILENO);
        }
        execlp("java", "java", "-version", (char *)NULL);
        _exit(127);
    }
    int status = 0;
    while (waitpid(pid, &status, 0) < 0 && errno == EINTR)
        ;
    return WIFEXITED(status) && WEXITSTATUS(status) == 0;
}

static const char RC_LIVE_DB[] = "db_ipc = run/tetrisdb.sock\n"
                                 "db_timeout = 4000\n"
                                 "auth_pbkdf2_iters = " TEST_ITERS "\n";

static const char RC_LIVE_DB_TWO_ATTEMPTS[] =
    "db_ipc = run/tetrisdb.sock\n"
    "db_timeout = 4000\n"
    "auth_max_attempts = 2\n"
    "auth_pbkdf2_iters = " TEST_ITERS "\n";

static pid_t g_runner = -1;

static void stop_runner(void)
{
    if (g_runner <= 0)
        return;
    kill(g_runner, SIGTERM);
    while (waitpid(g_runner, NULL, 0) < 0 && errno == EINTR)
        ;
    g_runner = -1;
    (void)unlink(WIRE_SOCK);
}

/*
 * recover = 0 is load-bearing rather than tuning, for the reason
 * tests/test_db.c records: SimpleDB's write-ahead log is a file
 * called "log" in the CURRENT DIRECTORY, shared by every runner ever started
 * from the repo root, while this table is created fresh for each run - so the
 * startup recovery pass would replay a previous run's records onto a brand new
 * heap file.
 */
static int start_runner(void)
{
    db_runner_opts_t opts;

    CHECK(db_ensure_table(WIRE_DB, TETRISAUTH_DB_TABLE, TETRISAUTH_DB_SCHEMA) ==
              0,
          "fixture: create the user table");

    /* ADR 0002 step 3, for the same reason the launcher does it: a process
     * killed while holding the semaphore leaves it at zero, and a named POSIX
     * semaphore outlives every process that ever touched it. Without this, one
     * interrupted run of this suite would make every later run's registration
     * cases wait out REG_WAIT_MS and fail. */
    (void)sem_unlink("/tetrish_register");

    memset(&opts, 0, sizeof(opts));
    snprintf(opts.java, sizeof(opts.java), "%s", DB_DEFAULT_JAVA);
    snprintf(opts.dir, sizeof opts.dir, "%s", WIRE_DB);
    snprintf(opts.jar, sizeof opts.jar, "%s", TEST_JAR);
    snprintf(opts.ipc, sizeof opts.ipc, "%s", WIRE_SOCK);
    opts.sessions = 8;
    opts.recover = 0;

    g_runner = db_runner_spawn(&opts, -1);
    CHECK(g_runner > 0, "fixture: spawn a runner");
    CHECK(db_runner_wait(WIRE_SOCK, g_runner, 20000) == 0,
          "fixture: the runner never accepted a connection");
    return 0;
}

/* One statement on a connection of this process's own, for the fixtures and
 * the assertions that read the table directly. */
static int query(const char *sql, char *body, size_t cap)
{
    db_socket_opts_t opts;

    memset(&opts, 0, sizeof(opts));
    snprintf(opts.sock, sizeof opts.sock, "%s", WIRE_SOCK);
    opts.timeout_ms = 8000;

    db_socket_t *conn = db_socket_open(&opts);
    if (conn == NULL)
        return -1;

    db_status_t st = db_socket_exec(conn, sql, body, cap);
    db_socket_close(conn);
    return st == DB_OK ? 0 : -1;
}

/* How many rows carry this name. -1 if the answer is not a table. */
static int rows_named(const char *name)
{
    char sql[256];
    char body[4096];

    snprintf(sql, sizeof sql,
             "select id from " TETRISAUTH_DB_TABLE " where name = '%s';", name);
    if (query(sql, body, sizeof body) != 0)
        return -1;
    return db_row_count(body);
}

static int child_name_is(session_t *sh, const char *want)
{
    char name[MAX_USER_NAME];

    if (auth_retry_handler(sh) != AUTH_OK)
        return 1;
    auth_get_name(name, sizeof name);
    return strcmp(name, want) == 0 ? 0 : 2;
}

static int child_alice(session_t *sh)
{
    return child_name_is(sh, "alice");
}
static int child_bobuser(session_t *sh)
{
    return child_name_is(sh, "bobuser");
}

/* REGISTER hands back an authenticated identity directly, and the token in the
 * 200's body is a real token under the secret on disk. Nothing in tetriSH
 * verifies one, so this is the only place it is ever checked - which is
 * exactly why token_verify() exists. */
static int peer_register_alice(session_t *cli)
{
    char token[TOKEN_MAX_LEN];
    unsigned char secret[64];
    token_claims_t claims;

    CHECK(put(cli, "REGISTER", "/auth/register", "Alice\ncorrect-horse") == 0,
          "send REGISTER");
    CHECK(get(cli, token, sizeof token) == 200, "REGISTER must be 200");

    int len = auth_secret_load(WIRE_ROOT, secret, sizeof secret);
    CHECK(len > 0, "the fixture secret must load");
    CHECK(token_verify(token, secret, (size_t)len, time(NULL), &claims) == TOKEN_OK,
          "the 200 body must be a token this secret verifies");
    CHECK(strcmp(claims.name, "alice") == 0,
          "the token's name must be the folded username");
    CHECK(claims.sub >= 1, "the token's sub must be the allocated user id");
    CHECK(claims.exp > claims.iat, "the token must expire after it was issued");
    return 0;
}

static int test_register_mints_a_token(void)
{
    wire_case_t w = {RC_LIVE_DB, child_alice, peer_register_alice};

    CHECK(drive(&w) == 0, "the registration exchange");
    CHECK(rows_named("alice") == 1,
          "registration must have written exactly one row");
    return 0;
}

/* Typed casing is not preserved, because there is no UPDATE to fix it with -
 * so `BobUser` registers and `BOBUSER` logs in, and both are `bobuser` on the
 * roster forever. */
static int peer_register_bob(session_t *cli)
{
    CHECK(put(cli, "REGISTER", "/auth/register", "BobUser\npassphrase") == 0,
          "send REGISTER");
    CHECK(get(cli, NULL, 0) == 200, "REGISTER must be 200");
    return 0;
}

static int peer_login_bob_shouting(session_t *cli)
{
    CHECK(put(cli, "LOGIN", "/auth/login", "BOBUSER\npassphrase") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 200,
          "a differently cased name must be the same account");
    return 0;
}

static int test_names_are_case_folded(void)
{
    wire_case_t reg = {RC_LIVE_DB, child_bobuser, peer_register_bob};
    wire_case_t log = {RC_LIVE_DB, child_bobuser, peer_login_bob_shouting};

    CHECK(drive(&reg) == 0, "the registration exchange");
    CHECK(drive(&log) == 0, "the login exchange");
    CHECK(rows_named("bobuser") == 1, "only one row, under the folded name");
    CHECK(rows_named("BobUser") == 0,
          "nothing is stored under the typed casing");
    return 0;
}

/* A duplicate is 409, it does not count against the budget, and the client can
 * carry on and become a guest - which is the recovery the ambiguous-409 wording
 * in docs/libtetrisauth.md tells the user about. */
static int peer_duplicate(session_t *cli)
{
    CHECK(put(cli, "REGISTER", "/auth/register", "alice\nanother-password") ==
              0,
          "send REGISTER");
    CHECK(get(cli, NULL, 0) == 409, "a duplicate username must be 409");

    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200, "a 409 must not have spent an attempt");
    return 0;
}

static int test_duplicate_registration_is_409(void)
{
    wire_case_t w = {RC_LIVE_DB, child_expect_ok, peer_duplicate};

    CHECK(drive(&w) == 0, "the duplicate exchange");
    CHECK(rows_named("alice") == 1,
          "a refused registration must write nothing");
    return 0;
}

static int peer_login_alice(session_t *cli)
{
    CHECK(put(cli, "LOGIN", "/auth/login", "alice\ncorrect-horse") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 200, "the right password must be 200");
    return 0;
}

static int test_login_succeeds(void)
{
    wire_case_t w = {RC_LIVE_DB, child_alice, peer_login_alice};
    return drive(&w);
}

/*
 * 404 and 401 are distinguishable, and both count. With auth_max_attempts at
 * 2, the second one drops the connection - so this case pins the status split
 * (#47 decision 13) and the cap (#56) at once, and the drop is observed as the
 * peer's next read failing rather than as anything on the wire.
 */
static int peer_two_failures_then_drop(session_t *cli)
{
    CHECK(put(cli, "LOGIN", "/auth/login", "alice\nwrong-password") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 401, "a wrong password must be 401");

    CHECK(put(cli, "LOGIN", "/auth/login", "nosuchuser\nwhatever") == 0,
          "send LOGIN");
    CHECK(get(cli, NULL, 0) == 404, "an unknown username must be 404");

    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == -1,
          "the connection must be gone after auth_max_attempts failures");
    return 0;
}

static int test_401_and_404_count_and_drop(void)
{
    wire_case_t w = {RC_LIVE_DB_TWO_ATTEMPTS, child_expect_drop,
                     peer_two_failures_then_drop};
    return drive(&w);
}

/*
 * The semaphore's own budget, and a second guard that it is taken at all.
 *
 * This process holds "/tetrish_register", so the session waits for a turn it
 * never gets and answers 500 - the runner is up and healthy throughout, so a
 * build that dropped the semaphore would answer 200 and write a row here. That
 * makes this the only case besides the sweep that fails when the serialization
 * is removed.
 *
 * It also pins the budget's existence rather than its length: the assertion is
 * that a 500 arrives at all, under the child's alarm(), with no elapsed time
 * compared against anything.
 */
static int peer_register_while_held(session_t *cli)
{
    CHECK(put(cli, "REGISTER", "/auth/register", "blocked\npassphrase") == 0,
          "send REGISTER");
    CHECK(get(cli, NULL, 0) == 500,
          "a registration that never gets a turn must be 500, not a hang");

    /* The documented recovery from any 500: continue as a guest. It also
     * asserts the 500 spent no attempt. */
    CHECK(put(cli, "GUEST", "/auth/guest", NULL) == 0, "send GUEST");
    CHECK(get(cli, NULL, 0) == 200,
          "a blocked registration must not end the session");
    return 0;
}

static int test_semaphore_wait_is_bounded(void)
{
    wire_case_t w = {RC_LIVE_DB, child_expect_ok, peer_register_while_held};

    sem_t *sem = sem_open("/tetrish_register", O_CREAT, 0600, 1);
    CHECK(sem != SEM_FAILED, "fixture: open the registration semaphore");
    CHECK(sem_trywait(sem) == 0, "fixture: hold the registration semaphore");

    int rc = drive(&w);

    sem_post(sem);
    sem_close(sem);

    CHECK(rc == 0, "the blocked registration exchange");
    CHECK(rows_named("blocked") == 0,
          "a registration that never got its turn must write nothing");
    return 0;
}

/*
 * LOAD-BEARING. Four processes registering the same username at once, swept
 * over a growing table.
 *
 * Four children against an EMPTY table all land on page 0, which has free
 * slots, and there the transaction alone is sufficient - so a single-shot
 * version of this case passes on a build with the semaphore deleted. The
 * semaphore's entire reason for existing is the append onto a FULL last page,
 * which is why this sweeps rather than races once. It deliberately does not
 * encode the page size or the row width: it fills, races, fills more, races
 * again, so it keeps crossing page boundaries the day a column is added.
 */
#define SWEEP_ROUNDS 16
#define RACERS 4

static int fill_rows(int first_id, int n)
{
    char sql[512];
    char body[2048];

    for (int i = 0; i < n; i++)
    {
        snprintf(sql, sizeof sql,
                 "insert into " TETRISAUTH_DB_TABLE " values (%d, 'filler%d', "
                 "'00112233445566778899aabbccddeeff', "
                 "'00112233445566778899aabbccddeeff"
                 "00112233445566778899aabbccddeeff', 1000, 0);",
                 first_id + i, first_id + i);
        if (query(sql, body, sizeof body) != 0)
            return -1;
    }
    return 0;
}

/* One round: RACERS processes send REGISTER for the same name at the same
 * time. Exactly one may be told 200. */
static int race_once(const char *name)
{
    int sv[RACERS][2];
    pid_t pid[RACERS];
    session_t cli[RACERS];
    char body[64];
    int accepted = 0, refused = 0;

    snprintf(body, sizeof body, "%s\nrace-password", name);

    for (int i = 0; i < RACERS; i++)
    {
        CHECK(socketpair(AF_UNIX, SOCK_STREAM, 0, sv[i]) == 0, "socketpair");
        pid[i] = fork();
        CHECK(pid[i] >= 0, "fork");
        if (pid[i] == 0)
        {
            session_t sh;

            for (int j = 0; j < i; j++)
                close(sv[j][0]);
            close(sv[i][0]);
            if (chdir(WIRE_ROOT) != 0)
                _exit(250);
            alarm(WATCHDOG_SECS);
            fake_session(&sh, sv[i][1]);
            _exit(auth_retry_handler(&sh) == AUTH_OK ? 0 : 1);
        }
        close(sv[i][1]);
        fake_session(&cli[i], sv[i][0]);
    }

    /* Every REGISTER goes out before any status is read, so the four of them
     * are genuinely contending rather than queueing behind this process's
     * reads. */
    for (int i = 0; i < RACERS; i++)
        CHECK(put(&cli[i], "REGISTER", "/auth/register", body) == 0,
              "send REGISTER");

    for (int i = 0; i < RACERS; i++)
    {
        int status = get(&cli[i], NULL, 0);
        if (status == 200)
            accepted++;
        else if (status == 409)
            refused++;
        else
            CHECK(0, "a racing REGISTER answered neither 200 nor 409");
    }

    for (int i = 0; i < RACERS; i++)
    {
        close(sv[i][0]);
        while (waitpid(pid[i], NULL, 0) < 0 && errno == EINTR)
            ;
    }

    CHECK(accepted == 1, "exactly one racing REGISTER may be accepted");
    CHECK(refused == RACERS - 1, "every other racer must be told 409");
    return 0;
}

static int test_registration_sweep(void)
{
    char name[MAX_USER_NAME];
    int next_filler = 100000;

    CHECK(wire_rc(RC_LIVE_DB) == 0, "fixture: write .tetrishrc");

    for (int round = 0; round < SWEEP_ROUNDS; round++)
    {
        CHECK(fill_rows(next_filler, round) == 0,
              "fixture: pre-fill the table");
        next_filler += round;

        snprintf(name, sizeof name, "racer%d", round);
        CHECK(race_once(name) == 0, "the four-process race");
        CHECK(rows_named(name) == 1,
              "the table must hold exactly one row for a raced username");
    }
    return 0;
}

int main(void)
{
    test_output_begin("test_auth");

    run("no socket: absent secret -> 500", test_absent_is_500);
    run("no socket: 0644 secret -> 500", test_loose_mode_is_500);
    run("no socket: 31-byte secret -> 500", test_short_secret_is_500);
    run("no socket: 65-byte secret -> 500", test_oversized_secret_is_500);
    run("no socket: a FIFO is refused on S_ISREG, not read",
        test_fifo_is_refused_not_read);
    run("no socket: 32-byte 0600 secret loads", test_valid_secret_loads);
    run("no socket: chmod 0600 recovers in the same process, no restart",
        test_chmod_recovers_without_restart);
    run("no socket: never repairs a loose existing secret",
        test_load_never_repairs);

    if (wire_setup() != 0)
    {
        test_output_failure_detail(
            "could not build the fixture root " WIRE_ROOT, __FILE__, __LINE__);
        test_output_fail("wire fixture setup");
        test_output_summary(tests_run + 1, tests_failed + 1, 0);
        return 1;
    }

    run("wire: GUEST succeeds with the database provably absent",
        test_guest_needs_no_database);
    run("wire: a client that hangs up is a drop", test_hangup_is_a_drop);
    run("wire: an unparseable frame is 400 and the exchange carries on",
        test_unparseable_frame_is_400);
    run("wire: a pre-auth 401 does not spend an attempt",
        test_pre_auth_401_does_not_count);
    run("wire: malformed credentials are 400 before any connection",
        test_malformed_credentials_are_400);
    run("wire: a legal 15-character name is not refused",
        test_legal_name_reaches_the_database);
    run("wire: a runner that never greets is a 500, not a hang",
        test_silent_runner_is_500);
    run("wire: no .tetrishrc fails LOGIN and leaves GUEST alone",
        test_missing_rc_splits_guest_from_login);
    run("wire: every auth method after login is 409, and the body is scrubbed",
        test_offer_always_refuses);

    if (!runner_disabled() && have_jar() && have_java())
    {
        if (start_runner() != 0)
        {
            tests_run++;
            tests_failed++;
            test_output_fail("runner integration test setup");
        }
        else
        {
            run("runner: REGISTER mints a token the secret verifies",
                test_register_mints_a_token);
            run("runner: usernames are folded to lowercase",
                test_names_are_case_folded);
            run("runner: a duplicate registration is 409 and writes nothing",
                test_duplicate_registration_is_409);
            run("runner: the right password is 200", test_login_succeeds);
            run("runner: 401 and 404 both count, and the cap drops the "
                "connection",
                test_401_and_404_count_and_drop);
            run("runner: a held registration semaphore is a 500, not a hang",
                test_semaphore_wait_is_bounded);
            run("runner: four-process registration sweep over a growing table",
                test_registration_sweep);
            stop_runner();
        }
    }
    else
    {
        /*
         * TETRISH_REQUIRE_RUNNER=1 turns this skip into a failure, for a CI job
         * that is not permitted to skip. A printed skip line is not a
         * mechanism: the jar is gitignored and CI has no JDK step, so this
         * repository is the proof that a skip becomes permanent and nobody
         * notices.
         */
        if (!runner_disabled() && getenv("TETRISH_REQUIRE_RUNNER") != NULL)
        {
            test_output_failure_detail(
                "TETRISH_REQUIRE_RUNNER is set and the runner tests could not "
                "run",
                __FILE__, __LINE__);
            tests_run++;
            tests_failed++;
            test_output_fail("runner integration tests are available");
        }
        else
        {
            test_output_skip("runner integration tests",
                             runner_disabled() ? "TETRISH_NO_RUNNER is set"
                             : !have_jar()     ? "no " TEST_JAR
                                             " - run `ant dist` in db/"
                                           : "no java on PATH");
            tests_skipped++;
        }
    }

    wire_reset();

    test_output_summary(tests_run + tests_skipped, tests_failed, tests_skipped);
    return tests_failed == 0 ? 0 : 1;
}
