/*
 * fuzz_jwt_verify.c - token_verify() on an attacker-supplied token.
 *
 * The name is historical: the format stopped being a JWT when token.c replaced
 * it - five newline-separated fields ending in a hex MAC, no base64url.
 *
 * The token is the one input to the auth path that a caller hands over
 * verbatim, before anything about them is known. token.c does its own field
 * splitting and its own decimal parsing (it may include nothing outside
 * OpenSSL - see name.h's note about the duplicated allowlist), so this is
 * hand-written parsing of hostile bytes with a security decision on the other
 * side of it.
 *
 * Two oracles, and the second is the one that matters:
 *
 *   1. Memory safety on any input (ASan/UBSan), plus the header's contract
 *      that *out is zeroed on every failure - a caller that reads claims
 *      after a non-OK return must not find the previous token's name there.
 *
 *   2. NO TOKEN THIS FUZZER INVENTS MAY VERIFY. The secret is fixed and
 *      private to this target, the fuzzer never sees it, and HMAC-SHA256 is
 *      not something a coverage-guided mutator will forge. So TOKEN_OK on
 *      fuzzer-generated bytes means the signature check can be bypassed -
 *      an auth bypass, not a crash. This is the highest-severity finding any
 *      target in this directory can produce, which is why it is an explicit
 *      check and not left to "did it segfault".
 *
 * The exception is the seed corpus: a genuinely valid token minted with this
 * same secret is seeded deliberately (so the fuzzer has real structure to
 * mutate from), and it must verify. Both directions are checked below by
 * re-minting: if the input equals a token we can mint ourselves, TOKEN_OK is
 * correct and anything else is a false rejection.
 */

#include "fuzz_support.h"
#include "jwt_fuzz_secret.h"
#include "auth.h" /* the token layer's private header; -I set in the Makefile */

#include <stdlib.h>
#include <string.h>

#define SECRET JWT_FUZZ_SECRET
#define FUZZ_NOW JWT_FUZZ_NOW

/* Could token_mint have produced exactly this token? Re-minting under the same
 * claims is the only honest way to ask - the alternative, trusting TOKEN_OK,
 * would make the oracle depend on the code it is testing. */
static int mintable(const char *token, const token_claims_t *claims) {
  char minted[TOKEN_MAX_LEN];
  if (token_mint(minted, sizeof minted, claims, SECRET, sizeof SECRET) != 0)
    return 0;
  return strcmp(minted, token) == 0;
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  /* token_verify takes a NUL-terminated string; the wire never hands it one,
   * the caller does. Terminate on the heap so a read past the end of the
   * token is an ASan report rather than a walk into the next allocation. */
  if (size > TOKEN_MAX_LEN * 4)
    return 0;
  char *token = (char *)malloc(size + 1);
  if (!token)
    return 0;
  memcpy(token, data, size);
  token[size] = '\0';

  token_claims_t out;
  memset(&out, 0xAA, sizeof out); /* poison: a "zeroed on failure" claim is
                                   * only meaningful if it was not already 0 */

  token_result_t rc = token_verify(token, SECRET, sizeof SECRET, FUZZ_NOW, &out);

  if (rc == TOKEN_OK) {
    /* Auth bypass unless we can mint the very same token ourselves. */
    FUZZ_CHECK(mintable(token, &out));
    /* A verified token's claims must be usable: the name is a C string and
     * exp is in the future, since verify is documented to reject now >= exp. */
    FUZZ_CHECK(fuzz_is_cstr(out.name, sizeof out.name));
    FUZZ_CHECK(out.exp > FUZZ_NOW);
  } else {
    /* token_verify(): *out is memset on entry and on every failure. */
    token_claims_t zero;
    memset(&zero, 0, sizeof zero);
    FUZZ_CHECK(memcmp(&out, &zero, sizeof out) == 0);
  }

  /* Verification is a pure function of (token, secret, now): same inputs,
   * same verdict. A second call disagreeing means state is leaking between
   * calls - which on a server means one request's outcome depending on the
   * previous request's token. */
  token_claims_t out2;
  memset(&out2, 0x55, sizeof out2);
  FUZZ_CHECK(token_verify(token, SECRET, sizeof SECRET, FUZZ_NOW, &out2) == rc);

  free(token);
  return 0;
}
